# Generated by Django 4.1.7 on 2023-04-02 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollment_number', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('roll_number', models.CharField(default='', max_length=4, unique=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(default='', max_length=10)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('address', models.TextField(default='')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.student')),
                ('course_name', models.CharField(choices=[('CO', 'Computer Engineering'), ('ME', 'Mechanical Engineering')], default='CO', max_length=50)),
                ('course_sem', models.CharField(choices=[('1', 'First Sem'), ('2', 'Second Sem'), ('3', 'Third Sem'), ('4', 'Fourth Sem'), ('5', 'Fifth Sem'), ('6', 'Sixth Sem')], default='1', max_length=1)),
                ('result_sem1', models.CharField(default='00', max_length=2)),
                ('result_sem2', models.CharField(default='00', max_length=2)),
                ('result_sem3', models.CharField(default='00', max_length=2)),
                ('result_sem4', models.CharField(default='00', max_length=2)),
                ('result_sem5', models.CharField(default='00', max_length=2)),
                ('result_sem6', models.CharField(default='00', max_length=2)),
            ],
        ),
    ]
