# Generated by Django 4.1.7 on 2023-04-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=4, unique=True),
        ),
    ]
